name = "IterativeNelderMead"
uuid = "cb660524-4ad9-4853-bda9-efa90ef41539"
authors = ["Bryson Cale <bryson.cale1@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
